baseurl                  = "https://hi.tmhmml.com"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Hi"
theme                    = "starter"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link, link will not be rendered if empty
    footerText           = "Hi, Tm Hmml"

# Metadata for Open Graph and Twitter
    description          = "Hi"               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Hi, Tm Hmml"
    # rss                = ""

[[params.videoBackground.sources]]
    source  = "/sample_video.mp4"
    type    = "video/mp4"
    poster  = "/background.png"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional

[[params.mainMenu]]
    link = "posts"
    text = "posts"

[imaging]
    quality = 75
